spring:
  application:
    name: Mock

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/mock

  datasource:
    url: jdbc:postgresql://localhost:5432/mock
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:Q09nfCQwRi9mO1JmfTx2MSRATWM1ajdNInI/MCZCX1BGd1JuLldHdy41JVkgQn5yTntSbiMlNDVdWTpRKGEiKVRYY2w8LHE=}
  expiration-ms: 3600000

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
